apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: udagram-frontend
          image: qngha7/udagram-frontend:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 80